### ISSUE TITLE
[Admin][Новини] Check the possibility of creating news exceeding the character limit in the fields

### ISSUE THREAD

**Issue by iskoryk** [ita-social-projects/StreetCode#1000]
**Priority:** Medium

**Preconditions**
1. Go to the site.
2. Login as admin.

**Steps to reproduce**
1. Go to field 'Новини' and click on 'Створити новину'.
2. Fill the title field with 101 characters and all mandatory fields according to requirements.
3. Fill the link field with 201 characters and all mandatory fields according to requirements.
4. Fill the text field with 15001 characters and all mandatory fields according to requirements. Click to button "Зберегти".

**Expected result**
2. Characters that exceed the limit are not added to the field title.
- [ ] 2. Characters that exceed the limit are not added to the field title.
- [ ] 3. Characters that exceed the limit are not added to the field link.
- [ ] 4. After entering characters the pop-up message appears "Ви перевищили максимально доступну кількість символів". After clicking "Зберегти" button field text becomes empty and the pop-up message appears "Не вдалося оновити/створити новину. Стпробуйте ще раз."

**User story:** #835
**Related bugs:** #854
