### ISSUE TITLE
[Admin][Новини] Verify the possibility of editing and deleting the news 

### ISSUE THREAD

**Issue by iskoryk** [ita-social-projects/StreetCode#1001]
**Priority:** Medium

**Preconditions**
1. Go to the site.
2. Login as admin.

**Steps to reproduce**
1. Go to field 'Новини'.
2. Click on the "pencil" button of any existing news.
3. Edit the text field: 
3.1. Add a new sentence.
3.2. Change the font settings - bold, italics, undo certain changes.
3.3. Delete part of the text.
3.4. Click on the "Зберегти" button.
4. Click on the "trash bin" button of any existing news.

**Expected result**
- [x] 2. The modal window of this news is open.
- [x] 3. All changes are saved.
- [x] 4. The selected news is deleted.

**User story:** #835
