### ISSUE TITLE
[Admin][Новини] Verify the possibility of creating a news without filling in the mandatory field

### ISSUE THREAD

**Issue by iskoryk** [ita-social-projects/StreetCode#1022]
**Priority:** Medium

**Preconditions**
1. Go to the site.
2. Login as admin.

**Steps to reproduce**
1. Go to field 'Новини' and click on 'Створити новину'.
2. Fill in fields:
2.1. Title, link, text.
2.2. Link, text, image.
2.3. Title, link, image.
2.4. Title, text, image.
3. Click the 'Зберегти' button.

**Expected result**
- [ ] 2.1. The popup window appears "Будь ласка, заповніть всі обовʼязкові поля". A tooltip appears below the image field "Додайте зображення".
- [ ] 2.2. The popup window appears "Будь ласка, заповніть всі обовʼязкові поля". A tooltip appears below the title field "Введіть заголовок".
- [ ] 2.3. The popup window appears "Будь ласка, заповніть всі обовʼязкові поля". A tooltip appears below the text field "Введіть текст".
- [ ] 2.4. The popup window appears "Будь ласка, заповніть всі обовʼязкові поля". A tooltip appears below the link field "Введіть посилання".

**User story:** #835
