### ISSUE TITLE
[Catalog] Verify that the StreetCodes gradually load as the user scrolls down the page

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/StreetCode#1060]
**Priority:**
High

**Preconditions**
1. At least 11-15 StreetCodes are added.

**Steps to reproduce**
1. Go to the site.
2. Click on the 'Стріткоди' in the burger menu.
3. Scroll down the page.

**Expected result**
StreetCodes gradually load as the user scrolls down the page:
- [ ] 5 cards per page width for desktop;
- [ ] 4 cards per page width for tablet;
- [ ] 2 cards per page width for mobile.

**Mockups:**
[Desktop](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=3319-6321&mode=design&t=GiaTKtcG9vApzvul-4)
[Tablet](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=3934-9438&mode=design&t=4QI6h4znlIBFV8M9-4)
[Mobile](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=3871-5634&mode=design&t=4QI6h4znlIBFV8M9-4)

**User story:**
#919
