### ISSUE TITLE
[API][StreetCode/Image/Catalog] When the 'imagesDetails' are deleted from the request body, the catalog on the frontend fails

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/StreetCode#1149]
**Environment:** All
**Reproducible:** Always
**Build found:** [61192c2](https://github.com/ita-social-projects/StreetCode/commit/61192c212ff01065c711324c06717333e907d8bb)

**Preconditions**
Open Postman.

**Steps to reproduce**
1. Choose the POST method.
2. Enter valid data in the mandatory fields from the API documentation in the body (/Streetcode/Create).
3. Clear the imagesDetails massif. (or:
- [x] without "alt" string in the "imagesDetails"
- [x] with "imagesDetails": null
- [x] without all massif "imagesDetails"
- [ ] with invalid "imagesIds": [4416] ).
4. Click the 'Send' button.
5. Open the StreetCode catalog in the frontend.

**Actual result**
The catalog disappeared in the frontend.

https://github.com/ita-social-projects/StreetCode/assets/135108144/5388f7d4-c454-4dee-a0ee-08a047fa22fc

**Expected result**
The response returns a '400 Bad Request' status, along with the message 'There is no valid "imagesDetails" value'.

**Postconditions**
DELETE the created StreetCode via id.

**User story and test case links**
User story #115

**Comment by SophiaMRI** [comment]
The catalog doesn't fail, but the admin can still create entries without image details, resulting in a Streetcode without a photo.

**Comment by arisssha** [comment]
When a POST request includes an invalid "imagesIds": [4416], the response returns a '400 Bad Request' status. However, the error message is incorrect: "Під час створення стріткоду сталася помилка. Повідомлення: An error occurred while saving the entity changes. See the inner exception for details."
