### ISSUE TITLE
Streetcode / Admin / Url with Transliteration

### ISSUE THREAD

**Issue by Tysyatsky** [ita-social-projects/StreetCode#147]
Short issue desc.: Adding transliteration in the link to the corresponding Streetcode.
 Main tasks: 
- [x] Transliteration link in the url to the streetcode.

Sub. tasks: 
- [x] Adding front- and backend validation for string for the format. Ex: taras-shevchenko.
- [x] Updating storage and creating a new field in database.
