### ISSUE TITLE
[Partners page] [Зворотній зв'язок] [Контакти page] When the user want to send the offer to become a partner, the system return the 401 status

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/StreetCode#1477]
**Environment:** All
**Reproducible:** Always
**Build found:** [79fb490](https://github.com/ita-social-projects/StreetCode/commit/79fb4900bc472c7efaf3e92e659797ccf1273ce6)

**Preconditions**
1. The admin went to the user who already had a burnt refresh token.
2. The site is open.

**Steps to reproduce**
1. Open the burger menu.
3. Click on the Burger menu and 'Партнери' button.
    Or scroll down to the footer and 'Партнери'.
4. Click on the 'Стати партнером' button on the right bottom or near the 'Задонатити' button.
5. Enter valid data in the fields.
6. Click on the captcha.
7. Click on the 'Відправити' button.
8. Repeat all steps with:
- [ ] Контакти->Форма зворотного зв’язку
- [ ] Форма зворотного зв’язку on the footer.
- [ ] Донати->Стати партнером.

**Actual result**
1. The modal window is closed.
2. The 'Щось пішло не так' message appears top of the page.

https://github.com/ita-social-projects/StreetCode/assets/135108144/ce9faa85-0a5a-44ec-93a7-0829142d7d45

**Expected result**
1. The modal window is closed.
3. The 'Лист успішно надісланий' message appears top of the page.

**User story and test case links**
User story #136 
[Test case] #1024
