### ISSUE TITLE
Improve Wow-Facts adaptivity

### ISSUE THREAD

**Issue by Kotusyk** [ita-social-projects/StreetCode#148]
The main goal of task is to fix and add new features in adaptivity of wow-fact block

One slide:
- [x] Make a working scroll for the text
- [x] Increase the spacing between letters and between lines
- [x] Increase the indents from the sides and make it adaptive

Many slides:
- [x] Increase the spacing between letters and between lines
- [ ] Modal windows should be the same size +- as the slides
- [x] Increase the indentation from the headers of the text block to the photo and to the text
- [ ] Fix adaptive, for expansion in 768 and 1024
- [ ] Increase indents to make it more adaptive
- [ ] Fix and slander the facts
- [x] Add pagination
