### ISSUE TITLE
Catalog Page

### ISSUE THREAD

**Issue by Tysyatsky** [ita-social-projects/StreetCode#160]
**Description**
Fully functional Catalog pages with Streetcodes. 

### Acceptance Criteria

- [x] Design according to Figma
- [x] Desktop version design
- [ ] Mobile and Tablet design
- [x] Getting all current streetcodes
- [x] Loading components on scroll
- [x] Redirect to the streetcode on click

### Tasks 
1. - [x] Getting all the Streetcodes
2. - [ ] Creating responsive design
3. - [x] Creating main design
4. - [x] Lazy loading components
5. - [x] On hover tags
