### ISSUE TITLE
Create DoD

### ISSUE THREAD

**Issue by PingvinAustr** [ita-social-projects/StreetCode#18]
## Task

- [ ] Create definition of done
- [ ] Create quality attributes&goals list
- [ ] Upload documentation to google drive
