### ISSUE TITLE
[Technical Task] Create a To-do website application

### ISSUE THREAD

**Issue by Michael-Kolpakov** [ita-social-projects/StreetCode#1839]
### Brief overview
You, as beginner interns will have to implement from zero a website on the topic of To-do list on both frontend and backend. To create it, you will need to use the technologies that are used on the main project. This is to allow you to get enough practice and knowledge base before going to the main project. The list of technologies is as follows:
- HTML, CSS
- React + TS
- React Hooks (optional)
- State management (MobX)
- AntDesign (optional)
- ASP.NET Core 8 Web API
- Entity Framework Core
- N-layer architecture
- AutoMapper (optional)
- Serilog (optional)
- Setup app in Docker locally (optional)
- Microsoft SQL Server

### Expected result
Fully functional website that can allow you to create tasks (which can have the status Pending, In Progress, Done), the ability to move them between statuses and if necessary delete or edit them.

### Additional Information
You can also add additional functionality if you wish, for example: displaying the date of task creation and the ability to sort tasks in each of the blocks by certain filters, etc.

### Attachments
To help you cope with the task can additional course on Udemy on creating a completed website using ASP.NET Core, React and MobX ([link](https://www.udemy.com/course/complete-guide-to-building-an-app-with-net-core-and-react/)).

**Indicate here what stage of readiness you are currently at:**
1. Yuliia:
- [x] Frontend is ready;
- [x] Backend is ready;
- [x] Everything is ready.
2. Vladyslav:
- [x] Frontend is ready;
- [x] Backend is ready;
- [x] Everything is ready.
3. Yaroslav:
- [x] Frontend is ready;
- [x] Backend is ready;
- [x] Everything is ready.
4. Ilya:
- [x] Frontend is ready;
- [x] Backend is ready;
- [x] Everything is ready.
5. Elizabeth:
- [x] Frontend is ready;
- [x] Backend is ready;
- [x] Everything is ready.
