### ISSUE TITLE
[TC][UI][Admin/Table of the streetodes catalog] Verify the contents of the streetcodes catalog table

### ISSUE THREAD

**Issue by crsc55** [ita-social-projects/StreetCode#1856]
**Priority:** High

**Preconditions**
1. User logged in as admin.
2. The "Стріткоди" tab is opened.

**Steps to reproduce**
- [ ] The "Назва стріткоду" column is in the table.
- [ ] The "Номер стріткоду" column is in the table.
- [ ] The "Автор" column is in the table.
- [ ] The "Статус" column is in the table.
- [ ] The "Останні зміни" column is in the table.
- [ ] The "Дії" column is in the table.

**User story:** #1160
