### ISSUE TITLE
[TC][Main][News]Verify сorrect display of elements on an Individual News Card and functionality of "Трохи ще" button.

### ISSUE THREAD

**Issue by Skyfall711** [ita-social-projects/StreetCode#1858]
**Priority:** medium

**Preconditions**

1. Go to the site.
2. Scroll down to 'News block'.

**Steps**

- [ ] 1. Check if a single news card contains an image, title, short description, and the button "До новини".
- [ ] 1.1. Check if clicking the button "Трохи ще" will redirect the user to a page with an entire article of the chosen news card.
- [ ] 1.2. Check if, on desktop/tablet/mobile, the user can click any area of the news card to redirect to an entire article
- [ ] 1.3. Verify that short description on a single news card is dynamically adjusts to the size of the card. When this limit is reached, an ellipsis appears followed by a "Трохи ще" link.

**Expected result**
All elements are displayed correctly on the individual card. When clicking on the area within the card or the "Трохи ще" link, the transition to the news page occurs. The short description on a single news card is dynamically adjusts to the size of the card. When this limit is reached, an ellipsis appears followed by a "Трохи ще" link.

**User story:** #696 
[Mockup](https://www.figma.com/design/jD2lHHBof7RrXWZqiUr0MU/HistoryCode?node-id=0-1&p=f&t=UX0qnlU6yKFUSX72-0)
