### ISSUE TITLE
[TC][Main][News] Verify correct display of news on diferent devices

### ISSUE THREAD

**Issue by Skyfall711** [ita-social-projects/StreetCode#1860]
**Priority:** medium

**Preconditions**
1. Go to the site.
2. Scroll down to 'News block'.

**Steps**

- [ ] 1. Verify how many news cards are displayed.
- [ ] 1.1. Verify on the Desktop, displaying 1 news card in the middle and 2 from left and right on the screen.
- [ ] 1.2. Verify on tablet/mobile, displaying only 1 news card in the middle of the screen.

**Expected result**
The cards are displayed correctly on different devices according to the [mockup](https://www.figma.com/design/jD2lHHBof7RrXWZqiUr0MU/HistoryCode?node-id=0-1&p=f&t=UX0qnlU6yKFUSX72-0)

**User story:** #696 

[Mockup](https://www.figma.com/design/jD2lHHBof7RrXWZqiUr0MU/HistoryCode?node-id=0-1&p=f&t=UX0qnlU6yKFUSX72-0)
