### ISSUE TITLE
[TC][Main][News] Verify the functionality of Indicator Squares (Pagination Squares) in the slider

### ISSUE THREAD

**Issue by Skyfall711** [ita-social-projects/StreetCode#1861]
**Priority:** medium

**Preconditions**
1. Go to the site.
2. Scroll down to 'News block'.

**Steps to reproduce**

- [ ] 1. Verify on desktop/tablet/mobile version the squares indicating the progress on switching news are present.
- [ ] 1.1. Check whether the number of squares corresponds to the number of news.
- [ ] 1.2. Check if selecting a specific square and clicking on it activates the square and redirects the user to the corresponding news card.
- [ ] 1.3. Check if selected square change depending on the news card being displayed.
- [ ] 1.4. Check if on desktop the corresponding news card of the selected square is located in the middle.
- [ ] 1.5. Check if on tablet/mobile the corresponding news card of the selected square is presented.

**Expected result**
The indicator squares are displayed according to the [mockup](https://www.figma.com/design/jD2lHHBof7RrXWZqiUr0MU/HistoryCode?node-id=0-1&p=f&t=UX0qnlU6yKFUSX72-0) and function correctly.

**Postconditions**
A clear and concise description of actions to be done after executing test. E.g.:

**User story:**#696

[Mockup](https://www.figma.com/design/jD2lHHBof7RrXWZqiUr0MU/HistoryCode?node-id=0-1&p=f&t=UX0qnlU6yKFUSX72-0)
