### ISSUE TITLE
[TC] [Main page] [Catalog of Streetcodes “Хочеш більше стріткодів?”] Verify that the block “Хочеш більше стріткодів?” are displayed according to the mockup.

### ISSUE THREAD

**Issue by virtusmanager13** [ita-social-projects/StreetCode#1883]
**Priority** 
   High

**Environment** 
   Desktop, tablet, mobile devices

**Preconditions**
   Main page is open. Find the block [Хочеш більше стріткодів?]

**Checklist**
- [x] Verify that block [Хочеш більше стріткодів?] situated under block [До стріткоду];
![Image](https://github.com/user-attachments/assets/f698ddc8-a1da-4d20-8c75-f9fa0b889032)
- [x] Verify that text match the text in mockup;
![Image](https://github.com/user-attachments/assets/c221d843-6298-46a7-a5d7-925af155fcce)
- [x] Verify that button situated according to the mockup;
Desktop
![Image](https://github.com/user-attachments/assets/04e0b04d-512f-4511-95e7-0070fe1712f0)
Tablet
![Image](https://github.com/user-attachments/assets/bade8266-51af-4663-8c86-33d47a04761e)
Mobile
![Image](https://github.com/user-attachments/assets/d3a0b554-e937-49c4-a2e1-83f1b3516f6b)
-[x] Verify that block [Хочеш більше стріткодів?] match the design according to mockup;
![Image](https://github.com/user-attachments/assets/55bd4060-e9a9-4e67-a987-91a0367df2ef)
![Image](https://github.com/user-attachments/assets/dc63a7a9-ee74-45f4-884a-b7cc977562c2)
![Image](https://github.com/user-attachments/assets/7df10d4a-ca90-4d9f-96fe-fbe820c688cd)
- [x] 7. Verify that elements do not interact with each other during window resize:
desktop (1920px, 1600px, 1025px), tablet (768px), mobile (360px).
-[x] Verify that elements do not interact with each other for 125% and 150% screen scale.

**Expected result**
Block [Хочеш більше стріткодів?] is displayed according to the mockup: on the desktop, tablet, and mobile devices.

**User story:**
#702

**Epic**
#694

**Related bug:**
