### ISSUE TITLE
[TC][Main Page] [Catalog of Streetcodes “Хочеш більше стріткодів?”] Verify that we can get possible to highlight text.

### ISSUE THREAD

**Issue by virtusmanager13** [ita-social-projects/StreetCode#1901]
**Priority:**
   Medium

**Environment** 
   Desktop, mobile, tablet devices.

**Preconditions**
   Main page is opened. Find the block [До стріткодів].

**Checklist**

- [ ] Highlight only one word, quickly double-click on it on desctop devices;
- [ ] Highlight the entire block of text, quickly triple-click on it on decstop devices;
- [ ] Press one word by finger to highlight only one word on mobile/tablet devices;
- [ ] Press one word by finger and and extend the selection to highlight the entire block of text on mobile/tablet devices.

User story
https://github.com/ita-social-projects/StreetCode/issues/702

Epic link
https://github.com/ita-social-projects/StreetCode/issues/694

Related bug:
**Related bug:**
