### ISSUE TITLE
[UI] [Menu] Verify that Menu corresponds to mockup

### ISSUE THREAD

**Issue by IrenIren78** [ita-social-projects/StreetCode#1920]
**Priority:**
Medium

**Preconditions**
1. The "Street code" main page is opened

- [ ] Check that the view of menu corresponds to mockup
- [ ] Check that the font style and size corresponds to mockup
- [ ] Check the spellind of menu text
- [ ] Check that the selected menu item become bigger and red (#891F16) according to mockup
- [ ] Check the presence of red (#891F16) square to the left of selected menu item according to mockup
- [ ] Check that the menu item is highlighted in red (#891F16) when user hovers over it

**Expected result**
The expanded Menu corresponds to mockup

**User story:**https://github.com/ita-social-projects/StreetCode/issues/962
