### ISSUE TITLE
[Admin/Chronology block] Verify that the admin can add different format of data.

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/StreetCode#370]
**Priority:**
High

**Preconditions**

1. The "StreetCode page" is opened.

2. Logged as admin.

**Steps to reproduce**

1. Scroll down to the "Chronology" block.

2. Сlick on the '+' button.

3. Enter combinations in the data fields:

- [ ] Year, day, month + '2000, 1 серпня'
- [ ] Year, day, month + '2000, серпень'
- [ ] Year, day, month + '2000'
- [ ] Year, day, month + '2000, літо'
- [ ] Year, month + '2000, серпень'
- [ ] Year, month + '2000'
- [ ] Year, month + '2000, літо'
- [ ] Year, month + '2000, 1 серпня'
- [ ] Year + '2000' 
- [ ] Year + '2000, літо'
- [ ] Year + '2000, 1 серпня'
- [ ] Year + '2000, серпень'
- [ ] Year, season + '2000, літо'
- [ ] Year, season + '2000, 1 серпня'
- [ ] Year, season + '2000, серпень'
- [ ] Year, season + '2000'

**Expected result**
Allowed combinations according to the table in story #39 

**User story:**
#124
