### ISSUE TITLE
[Streetcode page] [Adaptives] Different objects look not like on the mockup

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/StreetCode#644]
**Environment:** Windows 11, Chrome 115.0.5790.171 (Official Build) (64-bit)
**Reproducible:** Always
**Build found:** [a004670](https://github.com/ita-social-projects/StreetCode/commit/a0046702b7f8189d0bdc921662e67806cdf3d95f)

**Priority:** Low
**Severity:** Minor
**Type:** UI

**Preconditions:**
Streetcode page is present (e. g. http://20.120.82.146/roman-ratushnyi)

**Steps to reproduce:**
1. Scroll down to each object in brackets from the actual result
2. Compare with mockup

**Actual result:**
- [ ] 1. [Audio button] [from 1024 to 768px] 44px from the right end of the button and the right page's border ([screenshot](https://i.ibb.co/gzRnBNN/image.png))
- [x] 2. [Text's title] [from 365 to 360px] Goes beyond the right border ([screenshot](https://i.ibb.co/DwVY4jN/image.png))
- [x] 3. [Image figure of title] [Desktop/Mobile] Space between the end of the title's figure image and the start of the text [block is 55px](https://i.ibb.co/Hpv3sZZ/image.png) on desktop and [66px on mobile](https://i.ibb.co/gFDnNCH/image.png)
4. [Summary block/Image figure of title] [Desktop/Mobile] No space between the end of the summary block and the start of the text block on 
- [x] Desktop [(screenshot)](https://i.ibb.co/TMpvQtv/image.png), 
- [ ] 40px [on tablet](https://ibb.co/mypV1WM) and 
- [x] [12px on phone](https://i.ibb.co/1d1Py4Y/image.png)
- [ ] 5. [AR-history] [Desktop] The free space between the end of the objects container and the end of the AR-history block is 171px [(screenshot)](https://i.ibb.co/7zm8Bbw/image.png)
- [ ] 6. [Partners/AR-history] [Desktop/Mobile] The free space between the end of the AR-history and the start of the Partners is 
[108px on desktop](https://i.ibb.co/zHvBgVx/image.png), [54px on tablet](https://i.ibb.co/yyMyZqJ/image.png) and [49px on mobile](https://i.ibb.co/LxVtvD4/image.png)
- [x] 7. [Survey pop-up] [Mobile] The button "Пройти опитування" isn't centered [(screenshot)](https://i.ibb.co/TBKfGJh/Group-123.png)

**Expected result:**
1. [Audio button] 35px from the right end of the button and the right page's border ([mockup](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=4069-7980&mode=design&t=HlzvhGow65m9yu2l-4))
2. [Text's title] 11px from the end of the text container to the right border ([mockup](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=3555-8900&mode=design&t=HlzvhGow65m9yu2l-4))
3. [Image figure of text's title] [Desktop/Mobile] Space between the end of the title's figure image and the start of the text block is [26px on desktop [mockup]](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=5827-11490&mode=design&t=HlzvhGow65m9yu2l-4) and [10px on tablet/mobile [mockup]](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=4069-7992&mode=design&t=HlzvhGow65m9yu2l-4)
4. [Summary block/Image figure of title] [Desktop/Mobile] [110 px on desktop](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=5827-11490&mode=design&t=HlzvhGow65m9yu2l-4), [46px on tablet](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=4069-7992&mode=design&t=HlzvhGow65m9yu2l-4), [39px on mobile](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=3555-8898&mode=design&t=HlzvhGow65m9yu2l-4)
5. [Ar-history] [Desktop] The free space between the end of the objects container and the end of the AR-history block is 37px [(mockup)](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=5827-11813&mode=design&t=HlzvhGow65m9yu2l-4)
6. [Partners/AR-history] [Desktop/Mobile] The free space between the end of the AR-history and the start of the Partners is [30 px on desktop](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=5827-11826&mode=design&t=HlzvhGow65m9yu2l-4), [40px on tablet and mobile](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=4069-8674&mode=design&t=HlzvhGow65m9yu2l-4)
7. [Survey pop-up] [Mobile] The button "Пройти опитування" is centered [according to mockup](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=10167-8280&mode=design&t=HlzvhGow65m9yu2l-4)

Test case #614
Epic #19

**Comment by iskoryk** [comment]
1, 5, 6 errors are still reproduced
