### ISSUE TITLE
[Admin/Modal window with photo] If an admin save the data before the photo is uploaded and then close the modal window, the create request fails with a 500 error

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/StreetCode#949]
**Environment:** Windows 11,
Google Chrome Version 111.0.5563.147 (64-bit)
**Reproducible:** Always
**Build found:** [8490f60](https://github.com/ita-social-projects/StreetCode/commit/8490f607507e781d172f910b7e6859e64e055861)

**Preconditions**
1. The site is open.
2. Logged as admin.

**Steps to reproduce**
1. Go to the modal window.
2. Fill in all mandatory fields.
3. Add the photo and don't wait for the photo to download completely and click on the 'Зберегти' button.
4. Сlose the window.

**Actual result**
1. The 'Зберегти' button is disabled until the photo has been uploaded.
2. Despite a message appearing that indicates successful creation, the creation request fails with a 500 error.

https://github.com/ita-social-projects/StreetCode/assets/135108144/bbd25ec2-7312-4f0e-9aca-4d303ac33226

https://github.com/ita-social-projects/StreetCode/assets/135108144/2689262d-14f5-43ae-ad7f-aa24d3a54559

https://github.com/ita-social-projects/StreetCode/assets/135108144/53561d33-1ef4-4025-af1d-02dc2161a213

**Expected result**
The 'Зберегти' button is disabled until the photo has been uploaded.

Modal windows with these problems:
- [ ] [Partners]->'Створити партнера'
- [ ] [Для фанатів]->'Додати нову категорію'
- [ ] [Команда]->'Створити нового члена команди'

**Comment by SophiaMRI** [comment]
Still reproduce for [Для фанатів] category.

**Comment by Michael-Kolpakov** [comment]
Retest this issue one more time, please. It seems that, probably, issue can be already solved, otherwise we need more explanation about what is not working specifically right now.
