### ISSUE TITLE
[Main page][Tablet] The streetcode cards field does not look according to mockup

### ISSUE THREAD

**Issue by iskoryk** [ita-social-projects/StreetCode#983]
**Environment:** Tablet 768x1024
**Reproducible:** Always.
**Build found:** [8490f60](https://github.com/ita-social-projects/StreetCode/commit/8490f607507e781d172f910b7e6859e64e055861)

**Priority:** Medium
**Severity:** Trivial
**Type:** UI

**Preconditions**
1. Open the site as a user.

**Steps to reproduce**
1. Scroll down to 'Стріткоди'.
2. Flip through the streetcode cards.
3. Pay attention to the size of selected cards.

**Actual result**
- [ ] All displayed cards are the same size. 
- [ ] Displayed sometimes 4 cards (parts of first and fourth cards), sometimes 3 cards, but the second one is not in the center of the page. 
- [ ] There are a few navigation dots, but no cards are displayed if the user chooses these dots.

https://github.com/ita-social-projects/StreetCode/assets/130586498/035fc5ca-9504-40e7-94d2-859f64dbdc08

https://github.com/ita-social-projects/StreetCode/assets/130586498/71b7376e-c6df-4ccb-84b8-04dee15e0995

**Expected result**
Displayed 3 cards. The selected card has to be bigger according to the [mockup](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=8139-16302&mode=dev).
<img width="307" alt="Screenshot 2023-12-26 at 16 27 42" src="https://github.com/ita-social-projects/StreetCode/assets/130586498/e27680a8-733a-4056-9c46-8dc0f42e87bb">
Each navigation point has a corresponding streetcode card.

**User story:** #701
